spring:
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: [구글 클라이언트 아이디]
              clientSecret: [구글 클라이언트 패스워드]
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # http://localhost:8080/oauth2/callback/google
              scope: # 각 플랫폼마다 scope 가 다르므로 직접 방문해서 api 문서를 참고 바람
                - email
                - profile
            facebook:
              clientId: [페이스북 클라이언트 아이디]
              clientSecret: [페이스북 클라이언트 패스워드]
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # http://localhost:8080/oauth2/callback/facebook
              scope: # 각 플랫폼마다 scope 가 다르므로 직접 방문해서 api 문서를 참고 바람
                - email
                - public_profile
            github:
              clientId: [깃 허브 클라이언트 아이디]
              clientSecret: [깃 허브 클라이언트 패스워드]
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # http://localhost:8080/oauth2/callback/github
              scope: # 각 플랫폼마다 scope 가 다르므로 직접 방문해서 api 문서를 참고 바람
                - user:email
                - read:user
            naver:
              clientId: [네이버 클라이언트 아이디]
              client-secret: [네이버 클라이언트 패스워드]
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}" # http://localhost:8080/oauth2/callback/naver
              authorization-grant-type: authorization_code
              scope:
                - name
                - email
                - profile_image
              client-name: Naver
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
            naver:
              authorization_uri: https://nid.naver.com/oauth2.0/authorize # api 문서 참고
              token_uri: https://nid.naver.com/oauth2.0/token # api 문서 참고
              user-info-uri: https://openapi.naver.com/v1/nid/me # api 문서 참고
              user_name_attribute: response # api 문서 참고